---

- hosts: deploytargets
  vars_files:
    - secrets.yml
  tasks:
    - name: auth remote docker
      command: docker login {{ gitlab_reg }} -u {{ gitlab_reg_user }} -p {{ gitlab_reg_password }}

    - name: create writeable app dirs
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: "{{ appgroup }}"
        mode: 0770
      with_items:
        - "{{ approot }}"

    - name: create readable app dirs
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: "{{ appgroup }}"
        mode: 0750
      with_items:
        - "{{ assetdir }}"

    - name: create stash to archive working copy
      local_action: command git stash create
      args:
        chdir: ..
      run_once: true
      register: stash

    - name: expand ref
      local_action: command git rev-parse --verify {{ stash.stdout | default("HEAD", true) }}
      args:
        chdir: ..
      run_once: true
      register: revparse

    - name: create git archive
      local_action: command git archive {{ revparse.stdout }} -o docker-archive.tar
      args:
        chdir: ..
      run_once: true

    - name: build image
      local_action: command docker build -t {{ appname }}:staging -t {{ appname }}:{{ revparse.stdout }} -t {{ gitlab_repo }}/{{ appname }}:staging .
      args:
        chdir: ..
      run_once: true

    - name: push image
      local_action: command docker push {{ gitlab_repo }}/{{ appname }}:staging
      run_once: true

    - name: pull image
      command: docker pull {{ gitlab_repo }}/{{ appname }}:staging

    - name: tag remote image
      command: docker tag {{ gitlab_repo }}/{{ appname }}:staging {{ appname }}:staging

    - name: set app owner
      shell: "chown -R root:{{ appgroup }} {{ approot }}"

    - name: let app user read files
      shell: "chmod -R g+rX {{ approot }}"

    - name: let app user write db
      shell: "chmod g+w {{ approot }}/{{ appname }}_db.sqlite3; chmod g+w {{ approot }}"

    - name: disallow other users
      shell: "chmod -R o-rwx {{ approot }}"

- import_playbook: post_deploy.yml
