# Generated by Django 2.2.1 on 2019-06-16 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plug',
            name='serve_id',
        ),
        migrations.AddField(
            model_name='user',
            name='serve_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
