# Generated by Django 2.2.1 on 2019-06-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190616_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ga_tracking_id',
            field=models.TextField(blank=True, help_text='If set, impressions and clicks will be sent as events.', verbose_name='Google Analytics tracking id'),
        ),
    ]
