# Generated by Django 2.2.1 on 2019-06-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_ga_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plug',
            name='label',
        ),
        migrations.AddField(
            model_name='plug',
            name='domain',
            field=models.TextField(default='example.com', help_text='The domain of the site being linked to, eg "example.com". It will be matched against the request origin to prevent sites plugging themselves.'),
            preserve_default=False,
        ),
    ]
