# Generated by Django 2.2.1 on 2019-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190619_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='domain',
            field=models.TextField(help_text='The domain of the site being linked to, eg "example.com". Plugs will not be served to origins that are a direct match.'),
        ),
    ]
