# Generated by Django 2.2.1 on 2019-06-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190619_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='domain',
            field=models.TextField(help_text='The base domain of the site being linked to, eg "example.com". Plugs will not be served to origins with the same base domain.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ga_tracking_id',
            field=models.TextField(blank=True, help_text='If set, impressions and clicks will be sent as events to this property.', verbose_name='Google Analytics tracking id'),
        ),
    ]
