# Generated by Django 2.2.1 on 2019-07-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190620_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plug',
            name='domain',
            field=models.TextField(help_text='The domain of the site being linked to, eg <code>www.example.com</code>. Plugs will not be served to origins with the <i>exact</i> same domain (to prevent plugging a site a user is already on). Subdomains do not get special treatment; a www.example.com plug may be served to example.com or app.example.com.'),
        ),
        migrations.AlterField(
            model_name='plug',
            name='html_content',
            field=models.TextField(help_text='The HTML to replace your plug elements with, eg <code>Check out &lt;a href="http://www.example.com"&gt;my blog&lt;/a&gt;!</code>.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ga_tracking_id',
            field=models.TextField(blank=True, help_text='If set, impressions and clicks will be sent as events to this property. Requires setup in GA; see the docs for instructions.', verbose_name='Google Analytics tracking id'),
        ),
    ]
